//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EffortGroup.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceRepare
    {
        public int IdRep { get; set; }
        public Nullable<int> IdComp { get; set; }
        public Nullable<int> IdPer { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StartDataRep { get; set; }
        public Nullable<System.DateTime> EndDataRep { get; set; }
    
        public virtual Computers Computers { get; set; }
        public virtual Peripherals Peripherals { get; set; }
    }
}
