//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EffortGroup.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peripherals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Peripherals()
        {
            this.DeviceRepare = new HashSet<DeviceRepare>();
        }
    
        public int IdPer { get; set; }
        public string Type { get; set; }
        public Nullable<int> IdComp { get; set; }
        public string NamePer { get; set; }
        public string PhotoPer { get; set; }
    
        public virtual Computers Computers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceRepare> DeviceRepare { get; set; }
        public bool IsSelected { get; internal set; }
    }
}
